- name: variables preference/preceedence
  hosts: local
  connection: local
  vars:
    NAME: "Variable from Play"
  # vars_files:
  # - course.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter name
    private: false
  tasks:
  - name: print variables preference/preceedence
    # vars:
    #   NAME: "Variable from Tasks"
    ansible.builtin.debug:
      msg: "Hi {{ NAME }}"

# 1. Args
# 2. Tasks
# 3. File