- name: filters demo
  hosts: local
  connection: local
  vars:
    topics: linux, ansible, shell, terraform
    course: "DevOps with Ansible"
    myIP: "234.678.904.12"
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
    tagsList: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]
  tasks:
  - name: filters
    ansible.builtin.debug:
      msg: "Hi Ram Charan {{ greetings | default('Good morning')}}"
  
  - name: split filter & printing output
    ansible.builtin.debug:
      msg: "{{ topics | split(', ') }}"

  - name: map to list filter
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: list to map filter
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"
  
  - name: read students course.yaml
    ansible.builtin.set_fact: # setting the variable
      student_yaml: "{{ lookup('file', 'students.yaml') | from_yaml }}"
  
  - name: convert YAML to JSON
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"

  - name: convert to upper
    ansible.builtin.debug:
      msg: "{{ course | upper }}"

  - name: convert to lower
    ansible.builtin.debug:
      msg: "{{ course | lower }}"

  - name: check ipv4
    ansible.builtin.debug:
      msg: "{{ myIP | ansible.utils.ipv4 }}"
